// GENERATED by @omnifield/weber-vite — не редактировать руками.

import * as Views from './views';
import * as Widgets from './widgets';
import * as Entities from './entities';
import * as Features from './features';
export * as Views from './views';
export * as Widgets from './widgets';
export * as Entities from './entities';
export * as Features from './features';

/** Тотальный registry-объект для engine.register(registry). */
export const registry = {
  Views,
  Widgets,
  Entities,
  Controllers: {},
  Features,
  Shapes: {},
};
