/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Controller: typeof import('@weber-app/engine').Controller
  const Controllers: typeof import('@weber-app/registry').Controllers
  const Entities: typeof import('@weber-app/registry').Entities
  const Entity: typeof import('@weber-app/engine').Entity
  const Feature: typeof import('@weber-app/engine').Feature
  const Features: typeof import('@weber-app/registry').Features
  const Page: typeof import('@weber-app/engine').Page
  const Shape: typeof import('@weber-app/engine').Shape
  const Shapes: typeof import('@weber-app/registry').Shapes
  const View: typeof import('@weber-app/engine').View
  const Views: typeof import('@weber-app/registry').Views
  const Widget: typeof import('@weber-app/engine').Widget
  const Widgets: typeof import('@weber-app/registry').Widgets
  const useCompositeWrap: typeof import('@weber/kernel').useCompositeWrap
  const useCtx: typeof import('@weber/kernel').useCtx
  const useEmit: typeof import('@weber/logic').useEmit
  const useEmitOptional: typeof import('@weber/logic').useEmitOptional
}
