// GENERATED by @weber/vite — не редактировать руками.

export {};
declare global {
  const Entity: (typeof import('@weber-app/engine'))['Entity'];
  const View: (typeof import('@weber-app/engine'))['View'];
  const Shape: (typeof import('@weber-app/engine'))['Shape'];
  const Widget: (typeof import('@weber-app/engine'))['Widget'];
  const Page: (typeof import('@weber-app/engine'))['Page'];
  const Controller: (typeof import('@weber-app/engine'))['Controller'];
  const Feature: (typeof import('@weber-app/engine'))['Feature'];
  const useCtx: (typeof import('@weber/kernel'))['useCtx'];
  const useCompositeWrap: (typeof import('@weber/kernel'))['useCompositeWrap'];
  const useEmit: (typeof import('@weber/logic'))['useEmit'];
  const useEmitOptional: (typeof import('@weber/logic'))['useEmitOptional'];
  const Views: {
    readonly Counter: (typeof import('../src/views/counter'))['Counter'];
  };
  const Widgets: {
    readonly Counter: (typeof import('../src/widgets/counter'))['Counter'];
  };
  const Entities: {
    readonly Counter: (typeof import('../src/entities/counter'))['Counter'];
  };
  const Controllers: Record<string, never>;
  const Features: {
    readonly Counter: (typeof import('../src/features/counter'))['Counter'];
  };
  const Shapes: Record<string, never>;
}
