// GENERATED by @omnifield/weber-vite — не редактировать руками.
export {};
declare global {
  const Entity: (typeof import('@weber-app/engine'))['Entity'];
  const View: (typeof import('@weber-app/engine'))['View'];
  const Shape: (typeof import('@weber-app/engine'))['Shape'];
  const Widget: (typeof import('@weber-app/engine'))['Widget'];
  const Page: (typeof import('@weber-app/engine'))['Page'];
  const Controller: (typeof import('@weber-app/engine'))['Controller'];
  const Feature: (typeof import('@weber-app/engine'))['Feature'];
  const useCtx: (typeof import('@omnifield/weber-kernel'))['useCtx'];
  const useCompositeWrap: (typeof import('@omnifield/weber-kernel'))['useCompositeWrap'];
  const useEmit: (typeof import('@omnifield/weber-logic'))['useEmit'];
  const useEmitOptional: (typeof import('@omnifield/weber-logic'))['useEmitOptional'];
  const Views: typeof import('./registry/views');
  const Widgets: typeof import('./registry/widgets');
  const Entities: typeof import('./registry/entities');
  const Controllers: Record<string, never>;
  const Features: typeof import('./registry/features');
  const Shapes: Record<string, never>;
}
