/**
 * Registry barrel codegen — НАША уникальная часть build-infra (ADR-0002);
 * форма = barrel-registry предка (его ADR-034): НАСТОЯЩИЕ ES-модули с
 * re-export'ами → IDE-навигация в источник (боль №1 предка), честные типы
 * (боль №3), tree-shaking. Никакого globalThis (реестр = данные для
 * engine.register + unimport-глобалы поверх этих же барелей).
 *
 * Скан: `src/<layer>/` рекурсивно (*.ts / *.tsx) → дерево по папкам:
 *   leaf  → ИМЕНОВАННЫЙ ре-экспорт `export { LoginForm } from '<src>';`
 *           (pure named re-export ПРОЗРАЧЕН для Go-to-Definition — Ctrl+Click
 *           ведёт в ИСТОЧНИК, не в барель; находка user 2026-07-12).
 *           Fallback: файл без именованного экспорта = `export { default as X }`
 *           (навигация упрётся в барель — канон слоёв: `export const X = …;
 *           export default X;`, имя = PascalCase имени файла).
 *   mid   → `export * as Viewer from './viewer';`
 * Выход: `.weber/registry/<layer>/…` + корневой `index.ts`.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, posix, relative, resolve, sep } from 'node:path';
import type { IDtsMapping } from './declaration-map';
import { buildSourceMap, findDeclPosition } from './declaration-map';
import { toPascal } from './naming';

export const LAYERS = [
  'views',
  'widgets',
  'entities',
  'controllers',
  'features',
  'shapes',
] as const;
export type Layer = (typeof LAYERS)[number];

/** Namespace-имя слоя: views → Views. */
export const layerNamespace = (layer: Layer): string => toPascal(layer);

const SRC_EXT = /\.(tsx?|jsx?)$/;
const isSourceFile = (name: string): boolean =>
  SRC_EXT.test(name) && !name.endsWith('.d.ts') && !/\.(test|spec)\./.test(name);

interface TreeNode {
  /** подпапки */
  dirs: Map<string, TreeNode>;
  /** leaf-имя → абсолютный путь файла */
  leaves: Map<string, string>;
}

const emptyNode = (): TreeNode => ({ dirs: new Map(), leaves: new Map() });

const scanDir = (dir: string): TreeNode => {
  const node = emptyNode();
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      const child = scanDir(join(dir, entry.name));
      if (child.dirs.size || child.leaves.size) node.dirs.set(entry.name, child);
    } else if (isSourceFile(entry.name)) {
      node.leaves.set(entry.name, join(dir, entry.name));
    }
  }
  return node;
};

const toPosix = (p: string): string => p.split(sep).join(posix.sep);

/** Относительный import-спецификатор из barrel-файла к source-файлу (без расширения). */
const importSpecifier = (fromDir: string, toFile: string): string => {
  const rel = toPosix(relative(fromDir, toFile)).replace(SRC_EXT, '');
  return rel.startsWith('.') ? rel : `./${rel}`;
};

const HEADER = '// GENERATED by @weber/vite — не редактировать руками.\n';

/** Есть ли в файле ИМЕНОВАННЫЙ экспорт `name` (для прозрачной навигации). */
export const hasNamedExport = (source: string, name: string): boolean => {
  const decl = new RegExp(`export\\s+(?:const|let|var|function|class)\\s+${name}\\b`);
  if (decl.test(source)) return true;
  // export { X } / export { Y as X } (в т.ч. multiline)
  const clause = new RegExp(`export\\s*\\{[^}]*\\b(?:as\\s+)?${name}\\b[^}]*\\}`, 's');
  return clause.test(source);
};

/**
 * Генерирует карту barrel-файлов (относительный путь → содержимое) —
 * pure-функция от файловой структуры, тестируется без vite.
 */
export const generateRegistryFiles = (appRoot: string): Map<string, string> => {
  const out = new Map<string, string>();
  const srcDir = resolve(appRoot, 'src');
  const registryDir = resolve(appRoot, '.weber', 'registry');

  const presentLayers: Layer[] = [];

  const emitNode = (node: TreeNode, relDir: string): void => {
    const absDir = resolve(registryDir, relDir);
    const lines: string[] = [HEADER];
    for (const dirName of [...node.dirs.keys()].sort()) {
      lines.push(`export * as ${toPascal(dirName)} from './${dirName}';`);
      emitNode(node.dirs.get(dirName) as TreeNode, posix.join(relDir, dirName));
    }
    for (const fileName of [...node.leaves.keys()].sort()) {
      const abs = node.leaves.get(fileName) as string;
      const name = toPascal(fileName);
      const spec = importSpecifier(absDir, abs);
      // Именованный ре-экспорт прозрачен для GTD; default-алиас — fallback.
      const named = hasNamedExport(readFileSync(abs, 'utf8'), name);
      lines.push(
        named
          ? `export { ${name} } from '${spec}';`
          : `export { default as ${name} } from '${spec}';`,
      );
    }
    out.set(posix.join(relDir, 'index.ts'), `${lines.join('\n')}\n`);
  };

  for (const layer of LAYERS) {
    const layerDir = resolve(srcDir, layer);
    if (!existsSync(layerDir)) continue;
    const tree = scanDir(layerDir);
    if (!tree.dirs.size && !tree.leaves.size) continue;
    presentLayers.push(layer);
    emitNode(tree, layer);
  }

  // Корневой index: named-namespace re-export'ы (для unimport-глобалов) +
  // тотальный registry-объект (пустые слои — {}), для engine.register().
  const registryObject = LAYERS.map((l) =>
    presentLayers.includes(l) ? `  ${layerNamespace(l)},` : `  ${layerNamespace(l)}: {},`,
  ).join('\n');
  const rootContent = [
    HEADER,
    ...presentLayers.map((l) => `import * as ${layerNamespace(l)} from './${l}';`),
    ...presentLayers.map((l) => `export * as ${layerNamespace(l)} from './${l}';`),
    '',
    '/** Тотальный registry-объект для engine.register(registry). */',
    'export const registry = {',
    registryObject,
    '};',
    '',
  ].join('\n');
  out.set('index.ts', rootContent);

  return out;
};

/**
 * Генерит `.weber/globals.d.ts` + DECLARATION MAP (`globals.d.ts.map`) —
 * ЕДИНСТВЕННЫЙ источник ТИПОВ глобалов. Каждый leaf типизирован прямым
 * `typeof import('<файл-источник>')`, а карта редиректит Go-to-Definition
 * из декларации ПРЯМО в строку `export const X` источника (механизм
 * declarationMap «взрослых» либ — находка-раунды user 2026-07-12: и барели,
 * и голый d.ts дают лишний хоп; карта убирает его). unimport — ТОЛЬКО
 * runtime-инжект (dts выключен в defineWeberApp).
 */
export const generateGlobalsArtifacts = (appRoot: string): { dts: string; map: string } => {
  const srcDir = resolve(appRoot, 'src');
  const weberDir = resolve(appRoot, '.weber');

  const lines: string[] = [];
  const mappings: IDtsMapping[] = [];
  const push = (line: string) => lines.push(line);

  const emitNode = (node: TreeNode, indent: string): void => {
    for (const dirName of [...node.dirs.keys()].sort()) {
      push(`${indent}readonly ${toPascal(dirName)}: {`);
      emitNode(node.dirs.get(dirName) as TreeNode, `${indent}  `);
      push(`${indent}};`);
    }
    for (const fileName of [...node.leaves.keys()].sort()) {
      const abs = node.leaves.get(fileName) as string;
      const name = toPascal(fileName);
      const spec = importSpecifier(weberDir, abs);
      const source = readFileSync(abs, 'utf8');
      const member = hasNamedExport(source, name) ? name : 'default';
      const pos = findDeclPosition(source, name);
      mappings.push({
        generatedLine: lines.length,
        generatedColumn: indent.length + 'readonly '.length,
        // sources в карте — С расширением (реальный файл), не import-спецификатор.
        source: toPosix(relative(weberDir, abs)),
        sourceLine: pos.line,
        sourceColumn: pos.column,
      });
      push(`${indent}readonly ${name}: (typeof import('${spec}'))['${member}'];`);
    }
  };

  const emitRegistry = (): void => {
    for (const layer of LAYERS) {
      const ns = layerNamespace(layer);
      const layerDir = resolve(srcDir, layer);
      const tree = existsSync(layerDir) ? scanDir(layerDir) : emptyNode();
      if (!tree.dirs.size && !tree.leaves.size) {
        push(`  const ${ns}: Record<string, never>;`);
        continue;
      }
      push(`  const ${ns}: {`);
      emitNode(tree, '    ');
      push('  };');
    }
  };

  const wrapperDecls = ['Entity', 'View', 'Shape', 'Widget', 'Page', 'Controller', 'Feature'].map(
    (n) => `  const ${n}: (typeof import('@weber-app/engine'))['${n}'];`,
  );

  // HEADER содержит свой \n — в построчной сборке карта съехала бы на строку.
  for (const l of [HEADER.trimEnd(), 'export {};', 'declare global {']) push(l);
  for (const l of wrapperDecls) push(l);
  push("  const useCtx: (typeof import('@weber/kernel'))['useCtx'];");
  push("  const useCompositeWrap: (typeof import('@weber/kernel'))['useCompositeWrap'];");
  push("  const useEmit: (typeof import('@weber/logic'))['useEmit'];");
  push("  const useEmitOptional: (typeof import('@weber/logic'))['useEmitOptional'];");
  emitRegistry();
  push('}');
  push('//# sourceMappingURL=globals.d.ts.map');
  push('');

  return {
    dts: lines.join('\n'),
    map: buildSourceMap('globals.d.ts', mappings, lines.length),
  };
};

/** Совместимость: только текст d.ts. */
export const generateGlobalsDts = (appRoot: string): string =>
  generateGlobalsArtifacts(appRoot).dts;

/** Пишет барели + globals.d.ts(+map) на диск (перезапись только при изменении). */
export const writeRegistry = (appRoot: string): string[] => {
  const registryDir = resolve(appRoot, '.weber', 'registry');
  const files = generateRegistryFiles(appRoot);
  const written: string[] = [];
  const writeIfChanged = (abs: string, content: string) => {
    mkdirSync(resolve(abs, '..'), { recursive: true });
    if (existsSync(abs) && readFileSync(abs, 'utf8') === content) return;
    writeFileSync(abs, content, 'utf8');
    written.push(abs);
  };
  for (const [rel, content] of files) {
    writeIfChanged(resolve(registryDir, rel), content);
  }
  const globals = generateGlobalsArtifacts(appRoot);
  writeIfChanged(resolve(appRoot, '.weber', 'globals.d.ts'), globals.dts);
  writeIfChanged(resolve(appRoot, '.weber', 'globals.d.ts.map'), globals.map);
  return written;
};
